#ifndef CANIF_PBCFG_H
#define CANIF_PBCFG_H

#define PDUR_PDU_ID_EMOTION 0
#define PDUR_PDU_ID_SLEEP 1

#define PDUR_PDU_REV_EMOTION COM_PDU_ID_EMOTIONPDU
#define PDUR_PDU_REV_SLEEP COM_PDU_ID_SLEEPPDU

#endif //CANIF_PBCFG_H
