from PyQt5 import QtCore, QtGui, QtWidgets
from time import sleep
import numpy as np
from musicplayer import MusicPlayerWidget

class Ui_emoBoard_dialog(object):
    def setupUi(self, emoBoard_dialog):
        emoBoard_dialog.setObjectName("emoBoard_dialog")
        emoBoard_dialog.resize(320, 240)
        emoBoard_dialog.setWindowTitle("EmoDashboard")
        self.alpha_pixmap = QtGui.QPixmap("./imgs_pi/alpha.jpg")
        self.beta_pixmap = QtGui.QPixmap("./imgs_pi/beta.jpg")
        self.delta_pixmap = QtGui.QPixmap("./imgs_pi/delta.jpg")
        self.gamma_pixmap = QtGui.QPixmap("./imgs_pi/gamma.jpg")
        self.theta_pixmap = QtGui.QPixmap("./imgs_pi/theta.jpg")
        self.channel_list = QtWidgets.QComboBox(emoBoard_dialog)
        self.channel_list.setGeometry(QtCore.QRect(620/2.84, 570/2.83, 73/2.84, 22/2.83))
        self.channel_list.setObjectName("channel_list")
        self.channel_list.setToolTip("<html><head/><body><p>F3</p><p>FC5 </p><p>AF3 </p><p>F7 </p><p>T7 </p><p>P7 </p><p>O1</p><p>F4 </p><p>FC6 </p><p>AF4 </p><p>F8 </p><p>T8 </p><p>P8 </p><p>O2</p></body></html>")
        self.channel_label = QtWidgets.QLabel(emoBoard_dialog)
        self.channel_label.setGeometry(QtCore.QRect(550/2.84, 570/2.83, 55/2.84, 16/2.83))
        self.channel_label.setObjectName("channel_label")
        self.channel_label.setText("Channel")
        self.start_btn = QtWidgets.QPushButton(emoBoard_dialog)
        self.start_btn.setGeometry(QtCore.QRect(550/2.84, 620/2.83, 93/2.84, 28/2.83))
        self.start_btn.setObjectName("start_btn")
        self.start_btn.setText("Start")
        self.pause_btn = QtWidgets.QPushButton(emoBoard_dialog)
        self.pause_btn.setGeometry(QtCore.QRect(650/2.84, 620/2.83, 93/2.84, 28/2.83))
        self.pause_btn.setObjectName("pause_btn")
        self.pause_btn.setText("Stop")
        self.exit_btn = QtWidgets.QPushButton(emoBoard_dialog)
        self.exit_btn.setGeometry(QtCore.QRect(750/2.84, 620/2.83, 93/2.84, 28/2.83))
        self.exit_btn.setObjectName("exit_btn")
        self.exit_btn.setText("Exit")
        self.exit_btn.clicked.connect(self.quit)
        self.alpha_label = QtWidgets.QLabel(emoBoard_dialog)
        self.alpha_label.setGeometry(QtCore.QRect(30/2.84, 570/2.83, 55/2.84, 43/2.83))
        self.alpha_label.setObjectName("alpha_label")
        self.alpha_label.setPixmap(self.alpha_pixmap)
        self.beta_label = QtWidgets.QLabel(emoBoard_dialog)
        self.beta_label.setGeometry(QtCore.QRect(110/2.84, 570/2.83, 55/2.84, 43/2.83))
        self.beta_label.setObjectName("beta_label")
        self.beta_label.setPixmap(self.beta_pixmap)
        self.delta_label = QtWidgets.QLabel(emoBoard_dialog)
        self.delta_label.setGeometry(QtCore.QRect(190/2.84, 570/2.83, 55/2.84, 43/2.83))
        self.delta_label.setObjectName("delta_label")
        self.delta_label.setPixmap(self.delta_pixmap)
        self.gamma_label = QtWidgets.QLabel(emoBoard_dialog)
        self.gamma_label.setGeometry(QtCore.QRect(270/2.84, 570/2.83, 55/2.84, 43/2.83))
        self.gamma_label.setObjectName("gamma_label")
        self.gamma_label.setPixmap(self.gamma_pixmap)
        self.theta_label = QtWidgets.QLabel(emoBoard_dialog)
        self.theta_label.setGeometry(QtCore.QRect(350/2.84, 570/2.83, 55/2.84, 43/2.83))
        self.theta_label.setObjectName("theta_label")
        self.theta_label.setPixmap(self.theta_pixmap)
        self.signal_tabs = QtWidgets.QTabWidget(emoBoard_dialog)
        self.signal_tabs.setGeometry(QtCore.QRect(20/2.84, 70/2.83, 851/2.84, 441/2.83))
        self.signal_tabs.setObjectName("signal_tabs")
        self.tab_F34 = QtWidgets.QWidget()
        self.tab_F34.setObjectName("tab_F34")
        self.plot_widget_F34 = PlotWidget(self.tab_F34)
        self.plot_widget_F34.setGeometry(QtCore.QRect(10/2.84, 10/2.83, 821/2.84, 391/2.83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_F34.sizePolicy().hasHeightForWidth())
        self.plot_widget_F34.setSizePolicy(sizePolicy)
        self.plot_widget_F34.setInteractive(True)
        self.plot_widget_F34.setObjectName("plot_widget_F34")
        self.signal_tabs.addTab(self.tab_F34, "F3-F4")
        self.tab_FC56 = QtWidgets.QWidget()
        self.tab_FC56.setObjectName("tab_FC56")
        self.plot_widget_FC56 = PlotWidget(self.tab_FC56)
        self.plot_widget_FC56.setGeometry(QtCore.QRect(10/2.84, 10/2.83, 821/2.84, 391/2.83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_FC56.sizePolicy().hasHeightForWidth())
        self.plot_widget_FC56.setSizePolicy(sizePolicy)
        self.plot_widget_FC56.setInteractive(True)
        self.plot_widget_FC56.setObjectName("plot_widget_FC56")
        self.signal_tabs.addTab(self.tab_FC56, "FC5-FC6")
        self.tab_AF34 = QtWidgets.QWidget()
        self.tab_AF34.setObjectName("tab_AF34")
        self.plot_widget_AF34 = PlotWidget(self.tab_AF34)
        self.plot_widget_AF34.setGeometry(QtCore.QRect(10/2.84, 10/2.83, 821/2.84, 391/2.83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_AF34.sizePolicy().hasHeightForWidth())
        self.plot_widget_AF34.setSizePolicy(sizePolicy)
        self.plot_widget_AF34.setInteractive(True)
        self.plot_widget_AF34.setObjectName("plot_widget_AF34")
        self.signal_tabs.addTab(self.tab_AF34, "AF3-AF4")
        self.tab_F78 = QtWidgets.QWidget()
        self.tab_F78.setObjectName("tab_F78")
        self.plot_widget_F78 = PlotWidget(self.tab_F78)
        self.plot_widget_F78.setGeometry(QtCore.QRect(10/2.84, 10/2.83, 821/2.84, 391/2.83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_F78.sizePolicy().hasHeightForWidth())
        self.plot_widget_F78.setSizePolicy(sizePolicy)
        self.plot_widget_F78.setInteractive(True)
        self.plot_widget_F78.setObjectName("plot_widget_F78")
        self.signal_tabs.addTab(self.tab_F78, "F7-F8")
        self.tab_T78 = QtWidgets.QWidget()
        self.tab_T78.setObjectName("tab_T78")
        self.plot_widget_T78 = PlotWidget(self.tab_T78)
        self.plot_widget_T78.setGeometry(QtCore.QRect(10/2.84, 10/2.83, 821/2.84, 391/2.83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_T78.sizePolicy().hasHeightForWidth())
        self.plot_widget_T78.setSizePolicy(sizePolicy)
        self.plot_widget_T78.setInteractive(True)
        self.plot_widget_T78.setObjectName("plot_widget_T78")
        self.signal_tabs.addTab(self.tab_T78, "T7-T8")
        self.tab_P78 = QtWidgets.QWidget()
        self.tab_P78.setObjectName("tab_P78")
        self.plot_widget_P78 = PlotWidget(self.tab_P78)
        self.plot_widget_P78.setGeometry(QtCore.QRect(10/2.84, 10/2.83, 821/2.84, 391/2.83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_P78.sizePolicy().hasHeightForWidth())
        self.plot_widget_P78.setSizePolicy(sizePolicy)
        self.plot_widget_P78.setInteractive(True)
        self.plot_widget_P78.setObjectName("plot_widget_P78")
        self.signal_tabs.addTab(self.tab_P78, "P7-P8")
        self.tab_O12 = QtWidgets.QWidget()
        self.tab_O12.setObjectName("tab_O12")
        self.plot_widget_O12 = PlotWidget(self.tab_O12)
        self.plot_widget_O12.setGeometry(QtCore.QRect(10/2.84, 10/2.83, 821/2.84, 391/2.83))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget_O12.sizePolicy().hasHeightForWidth())
        self.plot_widget_O12.setSizePolicy(sizePolicy)
        self.plot_widget_O12.setInteractive(True)
        self.plot_widget_O12.setObjectName("plot_widget_O12")
        self.signal_tabs.addTab(self.tab_O12, "O1-O2")
        self.signal_tabs.setTabText(self.signal_tabs.indexOf(self.tab_FC56), "FC5-FC6")
        self.signal_tabs.setTabText(self.signal_tabs.indexOf(self.tab_AF34), "AF3-AF4")
        self.signal_tabs.setTabText(self.signal_tabs.indexOf(self.tab_F78), "F7-F8")
        self.signal_tabs.setTabText(self.signal_tabs.indexOf(self.tab_T78), "T7-T8")
        self.signal_tabs.setTabText(self.signal_tabs.indexOf(self.tab_P78), "P7-P8")
        self.signal_tabs.setTabText(self.signal_tabs.indexOf(self.tab_O12), "O1-O2")
        ##########
        ## self.tab_music = QtWidgets.QWidget()
        ## self.tab_music.setObjectName("tab_music")
        ## self.music_widget = MusicPlayerWidget(playlist=[], parent=self.tab_music)
        ## self.music_widget.setGeometry(QtCore.QRect(10, 10, 821, 391))
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.plot_widget_O12.sizePolicy().hasHeightForWidth())
        # self.music_widget.setSizePolicy(sizePolicy)
        ## self.music_widget.setObjectName("music_widget")
        ## self.signal_tabs.addTab(self.tab_music, "EmoMusicPlayer")
        ##########
        self.alpha_lcd = QtWidgets.QLCDNumber(emoBoard_dialog)
        self.alpha_lcd.setGeometry(QtCore.QRect(20/2.84, 620/2.83, 64/2.84, 23/2.83))
        self.alpha_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alpha_lcd.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.alpha_lcd.setLineWidth(5)
        self.alpha_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.alpha_lcd.setObjectName("alpha_lcd")
        self.beta_lcd = QtWidgets.QLCDNumber(emoBoard_dialog)
        self.beta_lcd.setGeometry(QtCore.QRect(100/2.84, 620/2.83, 64/2.84, 23/2.83))
        self.beta_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.beta_lcd.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.beta_lcd.setLineWidth(5)
        self.beta_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.beta_lcd.setObjectName("beta_lcd")
        self.delta_lcd = QtWidgets.QLCDNumber(emoBoard_dialog)
        self.delta_lcd.setGeometry(QtCore.QRect(180/2.84, 620/2.83, 64/2.84, 23/2.83))
        self.delta_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.delta_lcd.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.delta_lcd.setLineWidth(5)
        self.delta_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.delta_lcd.setObjectName("delta_lcd")
        self.gamma_lcd = QtWidgets.QLCDNumber(emoBoard_dialog)
        self.gamma_lcd.setGeometry(QtCore.QRect(260/2.84, 620/2.83, 64/2.84, 23/2.83))
        self.gamma_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.gamma_lcd.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.gamma_lcd.setLineWidth(5)
        self.gamma_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.gamma_lcd.setObjectName("gamma_lcd")
        self.theta_lcd = QtWidgets.QLCDNumber(emoBoard_dialog)
        self.theta_lcd.setGeometry(QtCore.QRect(340/2.84, 620/2.83, 64/2.84, 23/2.83))
        self.theta_lcd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.theta_lcd.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.theta_lcd.setLineWidth(5)
        self.theta_lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.theta_lcd.setObjectName("theta_lcd")

        """Remove curve and data to seperate class"""
        self.curve1 = self.plot_widget_F34.plot(pen='b')
        self.curve2 = self.plot_widget_F34.plot(pen='g')
        self.data = [0]
        self.data2 = [0]

        self.signal_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(emoBoard_dialog)
        

    def draw(self):
        line = '56'
        self.data.append(int(line))
        xdata1 = np.array(self.data, dtype='float64')
        line = '26'
        self.data2.append(int(line))
        xdata2 = np.array(self.data2, dtype='float64')
        self.curve1.setData(xdata1)
        self.curve2.setData(xdata2)
        sleep(1)
        app.processEvents()

    def quit(self):
        if QtGui.QMessageBox.question(None, '', "Are you sure you want to exit the EmoDashboard?",
            QtGui.QMessageBox.Yes | QtGui.QMessageBox.No, QtGui.QMessageBox.No) == QtGui.QMessageBox.Yes:
            app.quit()
        

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    emoBoard_dialog = QtWidgets.QDialog()
    ui = Ui_emoBoard_dialog()
    ui.setupUi(emoBoard_dialog)
    emoBoard_dialog.showFullScreen()
    timer = QtCore.QTimer()
    timer.timeout.connect(ui.draw)
    timer.start(0)
    sys.exit(app.exec_())

